Happyr/Doctrine-Specification

Upgrade.md
Should I write something more?
Ping @cakper @cordoval 
Fixing #65
=> Added a first attempt to document changes

src/Filter/In.php
=> Updated doc. The value parameter should be "mixed" not "string"

README.md, docs/0-0-symfony.md, docs/0-1-zend1.md, docs/0-2-zend2.md, docs/0-usage.md, docs/1-creatingSpecs.md
=> Updated docs to reflect the lastest version of the code

spec/Happyr/DoctrineSpecification/Query/LeftJoinSpec.php, src/Query/LeftJoin.php, src/Spec.php
Needed left join functionality so am submitting it in.
=> Add Left Join Spec

src/Query/AbstractJoin.php, src/Query/InnerJoin.php, src/Query/Join.php, src/Spec.php, tests/Query/InnerJoinSpec.php, tests/Query/LeftJoinSpec.php
Added innerJoin. To avoid too much code duplication I also created an AbstractJoin.
=> Created AbstractJoin and added innerJoin

src/Spec.php
Ok, I figured out that I was making my commits in GitHub via the text editor rather than through the git CLI, so the CLI couldn't squash the commits made online.  Anyways, here's the corrected code and this replaces #105 and #104
=> added notIn filter

src/EntitySpecificationRepositoryTrait.php, tests/EntitySpecificationRepositorySpec.php
Related to #116 
Also allow just apply specification without executing query. And apply it to different QueryBuilders with different dqlAliases.
=> Allow repository math Filter and QueryModifier.

src/Filter/InstanceOfX.php, src/Spec.php, tests/Filter/InstanceOfXSpec.php
Assert Entity is instance of class.
=> Filter: INSTANCE OF

src/Spec.php
Using reflection to get the arguments to the constructor
=> Fixed issue #120

src/EntitySpecificationRepository.php, src/EntitySpecificationRepositoryInterface.php
Created EntitySpecificationRepositoryInterface. Fixes #53
=> Specification Interface for Happyr/Doctrine-Specification#53

docs/0-usage.md
Doctrine repository interfaces is not required for EntitySpecificationRepositoryInterface
=> Fix error in docs code

src/Filter/Comparison.php, src/Filter/Equals.php, src/Filter/GreaterOrEqualThan.php, src/Filter/GreaterThan.php, src/Filter/LessOrEqualThan.php, src/Filter/LessThan.php, src/Filter/Like.php, src/Filter/NotEquals.php, src/Spec.php, src/Specification/CountOf.php
Is not a critical change.
Is a optimisations for code style
=> Add annotations

README.md
=> Fix minor issue with example usage QueryBuilder in docs

src/EntitySpecificationRepositoryInterface.php, src/EntitySpecificationRepositoryTrait.php
=> ResultModifier is nullable

src/Filter/MemberOfX.php, src/Spec.php, tests/Filter/MemberOfXSpec.php, tests/SpecSpec.php
=> Create MemberOfX filter

src/Filter/MemberOfX.php, src/Spec.php, tests/Filter/MemberOfXSpec.php, tests/SpecSpec.php
Fix #188
@patrickvale can you check this?
=> Correct MemberOfX spec

docs/0-usage.md, src/Operand/Field.php, src/Spec.php, tests/Operand/FieldSpec.php
=> Allow change field dql alias

README.md
After a [recent incident](https://github.com/PUGX/badge-poser/issues/260), i propose to move to a more reliable service.
=> Use shields.io for badges

.travis.yml, phpstan.neon.dist
https://github.com/phpstan/phpstan
=> Test project by PHPStan

composer.json
PRs for version 1.1 have already been merged into `master` branch.
We need to separate `1.0-dev` and` 1.1-dev` versions.
=> Change branch-alias for master to 1.1-dev

tests/Result/RoundDateTimeSpec.php
correct configure RoundDateTimeSpec as a spec and fix error in this spec.
=> RoundDateTimeSpec must extends ObjectBehavior

tests/Result/RoundDateTimeSpec.php
=> Remove not used vars in RoundDateTimeSpec

.gitignore
Allow customize configuration of [PHP Coding Standards Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer)
=> Allow customize PHP-CS-Fixer configuration

.styleci.yml, .travis.yml
Update Travis CI config and run code style test by [PHP CS Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer).
=> Update Travis CI config and run CS test by PHP CS Fixer

src/Filter/Comparison.php, src/Spec.php, tests/Filter/EqualsSpec.php, tests/Filter/GreaterOrEqualThanSpec.php, tests/Filter/GreaterThanSpec.php, tests/Filter/LessOrEqualThanSpec.php, tests/Filter/LessThanSpec.php, tests/Filter/NotEqualsSpec.php
Mark `Comparison` class as abstract.
Mark protected properties in `Comparison` class as private
=> Mark Comparison class as abstract

src/Logic/LogicX.php, tests/Logic/AndXSpec.php, tests/Logic/OrXSpec.php
Mark `LogicX` class as abstract.
=> Mark LogicX class as abstract

.github/workflows/test.yaml, composer.json
=> Build from GitHab CI fixes

.github/workflows/test.yaml, composer.json, src/Filter/InstanceOfX.php, tests/Filter/InstanceOfXSpec.php
Fix BC problems with Doctrine ORM 2.2 #257
=> Require Doctrine ORM 2.5

UPGRADE.md, composer.json, src/Query/AbstractJoin.php, src/Query/InnerJoin.php, src/Query/Join.php, src/Query/LeftJoin.php
=> Optimize build query in AbstractJoin query modifiers

.github/workflows/qa.yaml, UPGRADE.md, src/DBALTypesResolver.php, src/EntitySpecificationRepository.php, src/EntitySpecificationRepositoryInterface.php, src/EntitySpecificationRepositoryTrait.php, src/RepositoryFactory.php
=> Update PHPStan 12

src/Operand/Arithmetic.php
=> Remove not used Arithmetic::MOD constant
