Happyr/Doctrine-Specification

src/EntitySpecificationRepository.php
src/EntitySpecificationRepositoryTrait.php

This will address the issue in #53. 
EntitySpecificationRepository is left to make it backwards compatible.

Added Trait for EntitySpecificationRepository

---

Upgrade.md
src/BaseSpecification.php
src/Logic/LogicX.php

Made the `BaseSpecification` simpler by removing `getFilterInstance` and `getQueryModifierInstance`. Instead we divide these in `getFilter` and `modify`.
This address the issues in #83 and #84,

Make the api simpler

---

src/Spec.php
src/Specification/CountOf.php

This will address the issue in #80. 
Question: Do we really want to host complete `Specification`s like this?

Added CountOf specification

---

src/Logic/AndX.php
src/Logic/LogicX.php
src/Logic/OrX.php

A PR for the discussion in #45. 
Makes sure you can do something like: 
```php
public function search($parameters)
{
$spec = Spec::andX();
// ... If foo is set
$spec->andX(Spec::eq("foo", $parameters["foo"]);
// ... If bar is set
$spec->andX(Spec::eq("bar", $parameters["bar"]);
$finalSpec = Spec::orX(
$spec,
Spec::andX(Spec::lt("fizz", 4), Spec::eq("bing", 3))
);
$finalSpec->orX(Spec::gt("buzz", 99));
}
// Logic tree:
// (foo && bar) || (fizz && bing) || buzz
```
``` php
$spec = (Spec::AndX(A))->andX(B)->andX(C);
```

Making the API more fluent

---

src/Logic/Not.php

We don't have to check for `Specification`, the `QueryModifer` interface is enough. This allows you to have a class that implements both `Filter` and `QueryModifer` but is formerly not a `Specification`. Yes, very very rare but we should not check for a `Specification` if we only need to check for a `QueryModifer`.
This does also change the name from "parent" to "child" on the instance variable to be consistent with other `Filters`.

Check for QueryModifier instead of Specification

---

src/EntitySpecificationRepositoryTrait.php
tests/EntitySpecificationRepositorySpec.php

In doctrine/orm master they have changed the signature. We need to remove this line to be compliant to all versions of doctrine. ([Source](https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/EntityRepository.php#L79))

Removed abstract signature to be compliant with doctrine/orm 2.5

---

src/BaseSpecification.php
src/EntitySpecificationRepositoryTrait.php
src/Logic/LogicX.php
src/Logic/Not.php
src/Spec.php
src/Specification/CountOf.php
src/Specification/Specification.php
tests/EntitySpecificationRepositorySpec.php
tests/Filter/LikeSpec.php
tests/Logic/LogicXSpec.php
tests/Logic/NotSpec.php
tests/Result/AsArraySpec.php

Since we now got a folder named "Specification" we should move the `Specification` interface into it. This makes us consistent with the Filter, QueryModifier and ResultModifer interfaces. 
This is a BC break and the namespace will be awfully long (`Happyr\DoctrineSpecification\Specification\Specification`). Developers will, however, not use that namespace when they write their application code. 
I want to have some input on this PR before I merge it.

Moved Specification interface to Specification folder

---

src/EntitySpecificationRepositoryTrait.php

This address the issue in #85. This will add support for paginator.
```php
$spec = MySpec();
$query=$repo->prepare($spec);
$paginator = new Paginator($query);
```
As discussed in [this issue](https://github.com/rikbruil/Doctrine-Specification/issues/2); returning a Query will allow more flexibility but letting `match`-function return the query moves the responsibility to retrieve data up to the service layer. 
Please give me comments on this PR. How about the name of this function? I was also considering `getQuery`.

Added prepare function to return a Query

---

src/EntitySpecificationRepositoryTrait.php
tests/EntitySpecificationRepositorySpec.php

Hey!
Ran into a small problem today. If a specification won't generate a filter (i.e. returns `null`) then the query builder will generate DQL with broken syntax:
SELECT e FROM Foo\Bar e WHERE
So a simple fix is to just check whether an expression was generated or not.
Cheers,
Kristen

Make EntitySpecificationRepository accept specs not creating a filter

---

src/DBALTypesResolver.php
src/Filter/Comparison.php
src/Filter/In.php
src/ValueConverter.php

Fix for #133
[ValueObject](https://en.wikipedia.org/wiki/Value_object) must have `__toString()` method for convert it to query parameter.
Example usage:
```php
use MabeEnum\Enum;
class UserStatus extends Enum
{
const INACTIVE = 'i';
const ACTIVE   = 'a';
const DELETED  = 'd';
}
```
In spec 
```php
Spec::eq('status', UserStatus::ACTIVE());
```
**PS:** I not add tests for this solution becos i don't know how to use `phpspec`. Sorry

Add support ValueObject for Comparison filter

---

src/Query/Slice.php
src/Spec.php
tests/Filter/SliceSpec.php

Simplified scheme for dividing the query result into slices.
Before:
```php
$perPage = 20;
$currentPage = 2;
$videos = $rep->match(Spec::andX(
new VideoPublished(),
Spec::limit($perPage),
Spec::offset(($currentPage - 1) * $perPage)
);
```
After:
```php
$perPage = 20;
$currentPage = 2;
$videos = $rep->match(Spec::andX(
new VideoPublished(),
Spec::slice($perPage, $currentPage)
);
```

Add Slice query modifier

---

src/EntitySpecificationRepository.php

We don't need to reimplement explicitly these two interfaces in this concrete class because it extends `EntityRepository` which already implements them. So the new contract from https://github.com/Happyr/Doctrine-Specification/pull/134 is already satisfied in this class.

Remove double implementation of doctrine interfaces

---

src/EntitySpecificationRepositoryInterface.php
src/EntitySpecificationRepositoryTrait.php

Definition
====
Specifications describe the business rules and now we can use it only for selections.
It is not possible to use specifications for queries for updating and deletion of entities.
We are forced to duplicate the conditions.
Usage
====
Select only one field of entity by specification
```php
$country = $rep
->getQueryBuilder(Spec::andX(
Spec::neq('country', '')
Spec::limit(1)
), 'v')
->select('v.country')
->getQuery()
->getSingleScalarResult()
;
```
Update entities by specification
```php
$rep
->getQueryBuilder(Spec::eq('country', ''))
->update(null, 'v')
->set('v.country', ':country')
->setParameter('country', $country)
->getQuery()
->execute()
;
```
Delete entities by specification (#152)
```php
$rep
->getQueryBuilder($spec)
->delete()
->getQuery()
->execute()
;
```

Add method for get QueryBuilder by spec

---

src/Spec.php
src/Specification/CountOf.php
tests/Specification/CountOfSpec.php

Fix for #145 
Available use the filters as specification
```php
$total = (int) $rep->match(
Spec::сountOf(
Spec::eq('user', $user->getId()
),
new AsSingleScalar()
);
```
Available сount of all entities
```php
$total = (int) $rep->match(
Spec::сountOf(null),
new AsSingleScalar()
);
```

Сorrect param for CountOf specification

---

src/EntitySpecificationRepositoryInterface.php
src/EntitySpecificationRepositoryTrait.php
tests/EntitySpecificationRepositorySpec.php

Doctrine [AbstractQuery](https://github.com/doctrine/orm/blob/master/lib/Doctrine/ORM/AbstractQuery.php) has two scalar shortcut methods, would it be an idea to add them to this library? I'm aware the same result can be achieved by using result modifiers, but sometimes these shortcut methods come in handy.

Add scalar shortcut methods to repository

---

docs/0-usage.md
src/Operand/Alias.php
src/Operand/Field.php
src/Query/AbstractSelect.php
src/Query/AddSelect.php
src/Query/Select.php
src/Query/Selection/AbstractSelectAs.php
src/Query/Selection/ArgumentToSelectionConverter.php
src/Query/Selection/SelectAs.php
src/Query/Selection/SelectEntity.php
src/Query/Selection/SelectHiddenAs.php
src/Query/Selection/Selection.php
src/Spec.php
tests/Operand/AliasSpec.php
tests/Query/AddSelectSpec.php
tests/Query/SelectSpec.php
tests/Query/Selection/ArgumentToSelectionConverterSpec.php
tests/Query/Selection/SelectAsSpec.php
tests/Query/Selection/SelectEntitySpec.php
tests/Query/Selection/SelectHiddenAsSpec.php
tests/SpecSpec.php

This is a implementation of the selection control from #169 feature.
Selection single field:
```php
// DQL: SELECT e.email FROM ...
Spec::select('email')
// or
Spec::select(Spec::field('email'))
```
Add single field in the selected set:
```php
// DQL: SELECT e, u.email FROM ...
Spec::addSelect(Spec::field('email', $dqlAlias))
```
Add one more custom fields in the selected set:
```php
// DQL: SELECT e.title, e.cover, u.name, u.avatar FROM ...
Spec::andX(
Spec::select('title', 'cover'),
Spec::addSelect(Spec::field('name', $dqlAlias), Spec::field('avatar', $dqlAlias))
)
```
Add single entry in the selected set:
```php
// DQL: SELECT e, u FROM ...
Spec::addSelect(Spec::selectEntity($dqlAlias))
```
Use aliases for selection fields:
```php
// DQL: SELECT e.name AS author FROM ... …
```

Implementation of Selection concept

---

docs/0-usage.md
src/Operand/PlatformFunction.php
src/Spec.php
tests/Operand/PlatformFunctionSpec.php
tests/SpecSpec.php

This is a implementation of the Function operand from #169 feature.
Use functions:
```php
// DQL: SIZE(e.products) > 2
Spec::gt(Spec::SIZE('products'), 2);
// or
Spec::gt(Spec::fun('SIZE', 'products'), 2);
// or
Spec::gt(Spec::fun('SIZE', Spec::field('products')), 2);
```
Nested functions:
```php
// DQL: TRIM(LOWER(e.email)) = :email
Spec::eq(Spec::TRIM(Spec::LOWER('email')), trim(strtolower($email)));
// or
Spec::eq(
Spec::fun('TRIM', Spec::fun('LOWER', Spec::field('email'))),
trim(strtolower($email))
);
```

 Implementation of Function operand

---

docs/0-usage.md
src/Operand/BitAnd.php
src/Operand/BitLeftShift.php
src/Operand/BitNot.php
src/Operand/BitOr.php
src/Operand/BitRightShift.php
src/Operand/BitXor.php
src/Operand/Bitwise.php
src/Spec.php
tests/Operand/BitAndSpec.php
tests/Operand/BitLeftShiftSpec.php
tests/Operand/BitNotSpec.php
tests/Operand/BitOrSpec.php
tests/Operand/BitRightShiftSpec.php
tests/Operand/BitXorSpec.php
tests/SpecSpec.php

This is a implementation of the Bitwise operands from #169 feature.
You can use bitwise operations in specifications such as `&`, `|`, `^`, `<<`, `>>`, `~`.
For example, check the access for reading something with a bit mask:
```php
// DQL: (u.access & 0100) = 0100
$spec = Spec::eq(Spec::bAnd('access', UserAccess::READ), UserAccess::READ);
```
You can put bitwise operations in each other. For example, select not readed mails:
```php
// DQL: (m.status & (~ 0100)) = m.status
$spec = Spec::eq(
Spec::bAnd(
Spec::field('status'),
Spec::bNot(Spec::value(MailStatus::READED))
),
Spec::field('status')
);
```

Implementation of Bitwise operands

---

src/Query/IndexBy.php
src/Spec.php
tests/Query/IndexBySpec.php

This PR provides support for indexing resultsets by a given field.
```php
Spec::andX(
Speс::indexBy('thing');
);
```

Support for indexing results by arbitrary field

---

src/Specification/Having.php

This code
```php
$spec = Spec::andX(
Spec::gte('day', $this->start),
Spec::having(Spec::gt('views', 0)),
);
```
generate DQL
```
SELECT e FROM Entity e WHERE e.day >= :comparison_0 AND HAVING e.views > :comparison_1
```
and throw error
> [Syntax Error] line 0, col 148: Error: Expected Literal, got 'HAVING'
Spec `AndX` call [`Expr::andX()`](https://github.com/Happyr/Doctrine-Specification/blob/master/src/Logic/LogicX.php#L56) which create [`Doctrine\ORM\Query\Expr\Andx`](https://github.com/doctrine/orm/blob/master/lib/Doctrine/ORM/Query/Expr.php#L38) which extends [`Doctrine\ORM\Query\Expr\Composite`](https://github.com/doctrine/orm/blob/master/lib/Doctrine/ORM/Query/Expr/Base.php#L40) which extends [`Doctrine\ORM\Query\Expr\Base`](https://github.com/doctrine/orm/blob/master/lib/Doctrine/OR …

Having spec return NULL as filter

---

src/Operand/CountDistinct.php
src/Query/Distinct.php
src/Spec.php
tests/Operand/CountDistinctSpec.php
tests/Query/DistinctSpec.php
tests/SpecSpec.php

Add new fieature for use `DISTINCT` in queries.
```php
$rep->match(Spec::andX(
Spec::distinct(),
Spec::select('id'),
Spec::innerJoin('events', 'ev'),
Spec::eq('discount', true, 'ev')
));
```
DQL
```
SELECT DISTINCT e.id FROM Action e INNER JOIN e.events ev WHERE ev.discount = TRUE
```
```php
$rep->match(Spec::andX(
Spec::select(Spec::selectAs(Spec::countDistinct('id'), 'total')),
Spec::innerJoin('events', 'ev'),
Spec::eq('discount', true, 'ev')
));
```
DQL
```
SELECT COUNT(DISTINCT e.id) total FROM Action e INNER JOIN e.events ev WHERE ev.discount = TRUE
```

Add Distinct query modifier and CountDistinct operand

---

phpstan.neon.dist
src/Result/RoundDateTime.php

Fix error detected by PHPStan and level up to `2`.
* Call to an undefined method `DateTimeInterface::setTimestamp()`.

Call to an undefined method DateTimeInterface::setTimestamp().

---

phpstan.neon.dist
src/BaseSpecification.php
src/EntitySpecificationRepositoryInterface.php
src/EntitySpecificationRepositoryTrait.php
src/Logic/LogicX.php
src/Spec.php
src/Specification/Having.php

|  Line   |BaseSpecification.php
| ------ |-------------------------------------------------------------------------------------------------------------------------------
|  41     |Method Happyr\DoctrineSpecification\BaseSpecification::getFilter() should return string but empty return statement found.
|  63     |Method Happyr\DoctrineSpecification\BaseSpecification::getSpec() should return
|         |Happyr\DoctrineSpecification\Filter\Filter|Happyr\DoctrineSpecification\Query\QueryModifier but empty return statement found.
|  Line   |Spec.php
| ------ |----------------------------------------------------------------------------------------------------------------------------
|  121    |Method Happyr\DoctrineSpecification\Spec::andX() should return Happyr\DoctrineSpecification\Logic\AndX …

Fix PHPStan errors for level 3

---

phpstan.neon.dist
src/EntitySpecificationRepositoryTrait.php
src/Result/RoundDateTime.php

|  Line   |Result/RoundDateTime.php
| ------ |---------------------------------------------------------------------------------------------------
|  38     |Parameter # 1 `$unixtimestamp` of method `DateTimeImmutable::setTimestamp()` expects int, float given.
| Line   |EntitySpecificationRepositoryTrait.php (in context of class Happyr\DoctrineSpecification\EntitySpecificationRepository)  
| ------ |------------------------------------------------------------------------------------------------------------------------- 
|  202    |Result of && is always false.                                                                                            
|  207    |Else branch is unreachable because ternary operator condition is always                                                   true. …

Fix PHPStan errors for level 5

---

phpstan.neon.dist
src/Logic/LogicX.php
src/Operand/ArgumentToOperandConverter.php
src/Operand/PlatformFunction.php

|  Line   |Logic/LogicX.php
| ------ |----------------------------------------------------------------------------------------------------------------------------------
|  56     |Parameter # 1 `$function` of function `call_user_func_array` expects `callable()`: `mixed`, `array(Doctrine\ORM\Query\Expr, string)` given.
|  Line   |Operand/ArgumentToOperandConverter.php                                                                                                              
| ------ |-----------------------------------------------------------------------------------------------------------------------------------------------------
|  98     |Method `Happyr\DoctrineSpecification\Operand\ArgumentToOperandConverter::convert()` should return …

Fix PHPStan errors for level 6

---

phpstan.neon.dist
src/BaseSpecification.php
src/DBALTypesResolver.php
src/Filter/Comparison.php
src/Filter/In.php
src/Filter/InstanceOfX.php
src/Filter/Like.php
src/Operand/Alias.php
src/Operand/Field.php
src/Operand/Value.php
src/Query/AbstractJoin.php
src/Query/GroupBy.php
src/Query/IndexBy.php
src/Query/OrderBy.php
src/Spec.php

|  Line   |DBALTypesResolver.php
| ------ |------------------------------------------------------------------------------------------------------------
|  43     |Parameter # 1 `$key` of function `array_key_exists` expects `int\|string`, `string\|null` given.
|  44     |Parameter # 1 `$name` of static method `Doctrine\DBAL\Types\Type::getType()` expects string, `string\|null` given.
|  Line   |Filter/Comparison.php
| ------ |----------------------------------------------------------------------------------------------------------
|  82     |Property `Happyr\DoctrineSpecification\Filter\Comparison::$dqlAlias` (`string`) does not accept `string\|null`.
|  Line   |Filter/In.php
| ------ |--------------------------------------------------------------------------------------------------
|  37 …

Fix PHPStan errors for level 7

---

.php_cs.dist
.styleci.yml
src/DBALTypesResolver.php
src/Filter/Comparison.php
src/Logic/LogicX.php
src/Operand/Arithmetic.php
src/Operand/Bitwise.php
tests/Filter/ComparisonSpec.php
tests/Filter/InSpec.php
tests/Logic/LogicXSpec.php
tests/Operand/ArgumentToOperandConverterSpec.php
tests/Operand/PlatformFunctionSpec.php

[PSR-2](https://www.php-fig.org/psr/psr-2/) does not mention short array syntax, but in [chapter 4.3](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#43-methods) they use short array syntax to set the default value of `$arg3` to be an empty array.
So for PHP >= 5.4 the short array syntax seems to be the de-facto standard. The `array()` shold be used only for script to run on PHP < 5.4.

Use short array syntax recommended by PSR-2

---

src/Operand/ArgumentToOperandConverter.php
src/Operand/PlatformFunction.php

The expression `$arguments` of type `array<Happyr\DoctrineSpecification\Operand\Operand|string>` is implicitly converted to a boolean; are you sure this is intended? If so, consider using `empty($expr)` instead to make it clear that you intend to check for an array without elements.
Filename: `src/Operand/ArgumentToOperandConverter.php`
LineNumber: `73`
Link: https://scrutinizer-ci.com/g/Happyr/Doctrine-Specification/issues/master/files/src/Operand/ArgumentToOperandConverter.php?selectedLabels%5B0%5D=9&orderField=path&order=asc&honorSelectedPaths=0&issueId=36119903
It seems like `array_shift($arguments)` targeting `array_shift()` can also be of type `null`; however, `Happyr\DoctrineSpecification\Operand\ArgumentToOperandConverter::toField()` does only seem to accept …

Optimize convert several arguments to Operand

---

.travis.yml

Testing on lower versions of PHP increases project support for users using an older version of PHP.

Run PHPStan for low version of PHP

---

docs/0-usage.md

The doc was not explaining the easiest (IMO) way to make a repository support specs with the `match` method: the trait. It just takes adding one line to the class, and should be suggested.

Add a note on the repository trait

---

src/EntitySpecificationRepositoryTrait.php
src/Logic/LogicX.php

fix #232
The problem is that an empty filter appears that contains only spaces.
* Not apply expression for empty list of children specifications in `LogicX`;
* Clear filter from spaces to detect empty filter.

Empty filter

---

.php_cs.dist
.styleci.yml

The `single_line_throw` and `no_superfluous_phpdoc_tags` is not recommended.

Disable single_line_throw and no_superfluous_phpdoc_tags rules

---

.styleci.yml

Fix error in Style CI config
> Config Issue
> The 'short_array_syntax' fixer cannot be enabled again because it has already been enabled.

Remove short_array_syntax CS fixer

---

.styleci.yml

The `no_superfluous_phpdoc_tags`  fix rule has been added to the Style CI config, so we can disable it like in [.php_cs.dist](https://github.com/Happyr/Doctrine-Specification/blob/master/.php_cs.dist#L22).

Disable no_superfluous_phpdoc_tags in Style CI config

---

src/Filter/MemberOfX.php
src/Logic/LogicX.php
tests/Filter/MemberOfXSpec.php

Now `MemberOfX::getFilter()` return a stringable `\Doctrine\ORM\Query\Expr\Comparison` object and `LogicX::getFilter()` return a stringable `\Doctrine\ORM\Query\Expr\Andx` or `\Doctrine\ORM\Query\Expr\Orx` object.

MemberOfX::getFilter() and LogicX::getFilter() should return a string

---

.github/workflows/qa.yaml
.github/workflows/test.yaml
composer.json
tests/Operand/ArgumentToOperandConverterSpec.php

PHP 8 compatibility requires PHPSpec to be updated to `6.3`.
PHPSpec `6.3` [require](https://packagist.org/packages/phpspec/phpspec#6.3.0) PHP `^7.2`.

Update PHPSpec to 6.3 and PHP to 7.2

---

UPGRADE.md
docs/0-usage.md
src/Logic/AndX.php
src/Logic/LogicX.php
src/Logic/OrX.php
src/Operand/PlatformFunction.php
src/Query/AbstractSelect.php
src/Query/QueryModifierCollection.php
src/Result/ResultModifierCollection.php
src/Spec.php
tests/Operand/PlatformFunctionSpec.php
tests/Query/AddSelectSpec.php
tests/Query/SelectSpec.php

Use [variable-length argument lists](https://www.php.net/manual/en/functions.arguments.php#functions.variable-arg-list) in `AndX`, `OrX`, `Select`, `AddSelect`, `PlatformFunction`, `QueryModifierCollection` and `ResultModifierCollection`.
* Removes the ability to use `array` as argument for the `PlatformFunction` operand.
Before:
```php
$arguments = ['create_at', new \DateTimeImmutable()];
Spec::DATE_DIFF($arguments);
Spec::fun('DATE_DIFF', $arguments);
new PlatformFunction('DATE_DIFF', $arguments);
```
After:
```php
$arguments = ['create_at', new \DateTimeImmutable()];
Spec::DATE_DIFF(...$arguments);
Spec::fun('DATE_DIFF', ...$arguments);
new PlatformFunction('DATE_DIFF', ...$arguments);
```
* Removes the ability to use `array` as argument for the `Select` query modifier.
Before:
```php …
```

Use variable-length argument lists

---

UPGRADE.md
src/Exception/InvalidArgumentException.php
src/Exception/LogicException.php
src/Exception/NoResultException.php
src/Exception/NonUniqueResultException.php
src/Exception/UnexpectedResultException.php

* The `InvalidArgumentException` class marked as `final`.
* The `LogicException` class marked as `final`.
* The `NonUniqueResultException` class marked as `final`.
* The `NoResultException` class marked as `final`.
* The `UnexpectedResultException` class marked as `abstract`.

Change access for exception classes

---

src/EntitySpecificationRepositoryTrait.php
src/Exception/UnexpectedResultException.php
src/Filter/MemberOfX.php
src/Logic/Not.php
src/Operand/Addition.php
src/Operand/ArgumentToOperandConverter.php
src/Operand/Arithmetic.php
src/Operand/Division.php
src/Operand/Modulo.php
src/Operand/Multiplication.php
src/Operand/Subtraction.php
src/Query/AbstractJoin.php
src/Query/AbstractSelect.php
src/Query/OrderBy.php
src/Query/Selection/AbstractSelectAs.php
src/Query/Selection/SelectEntity.php
src/Result/AsArray.php
src/Result/AsScalar.php
src/Result/AsSingleScalar.php
src/Result/RoundDateTime.php
src/Spec.php
src/Specification/CountOf.php

* Fix typo in annotations;
* Add `ASC` and `DESC` constants in `OrderBy` spec;
* Rename some variables;
* Don't check that `$query->getParameters()` instance of `Parameter`. This is always true for Doctrine ORM `>= 2.3`

Pedantic fixes
